[phases.setup]
aptPkgs = [
  "chromium",
  "libglib2.0-0",
  "libnss3",
  "libfontconfig1",
  "libxss1",
  "libasound2t64",     # Changed from libasound2
  "libatk1.0-0",
  "libgtk-3-0",
  "xvfb"
]

[start]
cmd = "gunicorn api:app"